### ISSUE TITLE
Message fee configuration

### ISSUE THREAD

**Issue by davepuchyr** [iov-one/iovns#21]
Message fees must be mutable in order for IOV to have a viable pricing model.  Each fee will stem from parameters in an on-chain configuration object.  Fees are [formulaic](https://github.com/iov-one/iovns/issues/2#issuecomment-618900663) and require several pricing parameters.

Requirements:
- [ ] parameter names are not fixed
- [x] parameter values use sdk.Dec
- [x] parameters can be set or unset (added or removed from the configuration)
- [ ] any number of parameters can be set
- [ ] any given parameter can be (un)set without having to set all the other parameters
- [ ] only the IOV SAS multisig account can (un)set parameters
- [ ] removal of a parameter that would break the calculator should NOT be allowed
- [ ] the configuration can be queried

**Comment by fdymylja** [comment]
@davepuchyr  can we close this?
