### ISSUE TITLE
Create a database service for iovns

### ISSUE THREAD

**Issue by davepuchyr** [iov-one/iovns#229]
Some of our partners would prefer to deal with a database than a node.

- [x] Implement the database service spec
- [x] Add the service to the testnet cluster

**Comment by orkunkl** [comment]
I don't want to poll RPC endpoint as we did on block-metrics. Instead lets utilize cosmos sdk events. I will create an issue describing what needs to be done

**Comment by davepuchyr** [comment]
Closed via https://github.com/iov-one/iovns/pull/252 and https://github.com/iov-one/easy-testnets/pull/142.
