### ISSUE TITLE
Change `blockchain_id` to `uri` and `address` to `resource`

### ISSUE THREAD

**Issue by orkunkl** [iov-one/iovns#238]

**Comment by davepuchyr** [comment]
While we're clarifying nomenclature, how big a deal would it be to rename package `domain` to `starname`?

**Comment by orkunkl** [comment]
> While we're clarifying nomenclature, how big a deal would it be to rename package `domain` to `starname`?

It is not expensive but we should wait for @fdymylja orm implementation

**Comment by orkunkl** [comment]
What we should be the `BlockchainAddress` naming?

**Comment by davepuchyr** [comment]
> What we should be the `BlockchainAddress` naming?

Good question.  Answer: `UniformResource`.

**Comment by davepuchyr** [comment]
> > What we should be the `BlockchainAddress` naming?
> 
> Good question. Answer: `UniformResource`.

Frojdi ran with `Resource` and that works for me.
