### ISSUE TITLE
Usability 

### ISSUE THREAD

**Issue by Kwaskoff** [iov-one/iovns#381]
People need use your centralized web site for decentralized addresses?
Is the starname only records with decentralized addresses in your blockchain without your site?

**Comment by davepuchyr** [comment]
> People need use your centralized web site for decentralized addresses?
> Is the starname only records with decentralized addresses in your blockchain without your site?

People don't have to use our web site for starnames.  They can use the Cosmostation [mobile](https://play.google.com/store/apps/details?id=wannabit.io.cosmostaion) [wallet](https://itunes.apple.com/app/cosmostation/id1459830339?mt=8) or the [iovnscli](https://docs.starname.me/for-developers/tutorial#installing-the-cli) command-line tool.  

All the blockchain related starname info is on-chain and decentralized.  The starname profile image and info is persisted through Aleph into IPFS, so it's decentralized too.
