### ISSUE TITLE
Mainnet Setup Issue

### ISSUE THREAD

**Issue by wrayjohn157** [iov-one/iovns#386]
Hello, I am not sure where else to turn for help. I have followed the docs on mainnet setup and have my sentry gossiping while my validator node only syncs with the sentry. Both are synced to the chain tip and when i go live my uptime drops to zero then jailed. I have send email to the contact us and requested support on TG. 

Please help.

Kind Regards,
Ent.

**Comment by davepuchyr** [comment]
> Hello, I am not sure where else to turn for help. I have followed the docs on mainnet setup and have my sentry gossiping while my validator node only syncs with the sentry. Both are synced to the chain tip and when i go live my uptime drops to zero then jailed. I have send email to the contact us and requested support on TG.
> 
> Please help.
> 
> Kind Regards,
> Ent.

Are you using an HSM?  If not then make sure that your validator is using the correct `priv_validator_key.json`.  If you followed [these](https://docs.starname.me/for-validators/mainnet) setup instructions then `${DIR_WORK/config/priv_validator_key.json` is the one that matters.  In other words, make sure that `~/.iovnsd/config/priv_validator_key.json` isn't being used if it exists.

If you unjail your validator again you can check for its address in http://localhost:46657/dump_consensus_state.  You need to use the `priv_validator_key.json` file that has the address shown in dump_consensus_state.

If that doesn't help then I'll reach out to you via TG.

**Comment by wrayjohn157** [comment]
Victory!!!

Awesome, ty for the help, my private key was in .iovnsd by the default setup.. just a simple cp /home … /config and now up and running. I was going crazy trying to figure this out.. much appreciated!

Best,
Ent


[cid:image002.png@01D6D529.BF779930]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
